"""initial schema: 8 tables for X digest

Revision ID: 716d73449a12
Revises: 
Create Date: 2026-05-16 22:10:06.873353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '716d73449a12'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_call_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('denied_users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('denied_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('pending_requests',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('requested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('subscribers',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_by', sa.BigInteger(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_pushed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('x_authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('screen_name', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('user_id_x', sa.String(length=64), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_x_authors_screen_name'), 'x_authors', ['screen_name'], unique=True)
    op.create_table('tweets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('posted_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('reply_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('like_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('view_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('retweet_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('quote_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('media', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('permalink', sa.String(length=500), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scraped_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_metric_update_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['x_authors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tweets_author_id'), 'tweets', ['author_id'], unique=False)
    op.create_index(op.f('ix_tweets_posted_at'), 'tweets', ['posted_at'], unique=False)
    op.create_table('daily_digests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('digest_date', sa.Date(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('featured_tweet_id', sa.BigInteger(), nullable=True),
    sa.Column('other_tweet_ids', postgresql.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('summary_per_tweet', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('overall_takeaway', sa.Text(), nullable=True),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('model_used', sa.String(length=64), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['x_authors.id'], ),
    sa.ForeignKeyConstraint(['featured_tweet_id'], ['tweets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('digest_date', 'author_id', name='uq_digest_date_author')
    )
    op.create_table('push_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('digest_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('success', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['digest_id'], ['daily_digests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['subscribers.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('push_history')
    op.drop_table('daily_digests')
    op.drop_index(op.f('ix_tweets_posted_at'), table_name='tweets')
    op.drop_index(op.f('ix_tweets_author_id'), table_name='tweets')
    op.drop_table('tweets')
    op.drop_index(op.f('ix_x_authors_screen_name'), table_name='x_authors')
    op.drop_table('x_authors')
    op.drop_table('subscribers')
    op.drop_table('pending_requests')
    op.drop_table('denied_users')
    op.drop_table('ai_call_log')
    # ### end Alembic commands ###
